Добавил экраны избранных поездок и экран поиска поездок, добавил архитектуру
iOS-vk-education/2024_1_SunaTeam pull request #19
Opened 2024-12-15 23:44 UTC by IvanTarasiuk

Merge request Task 9 – Favorite Places screens

2024-12-16 13:06 UTC, blackplayerten requested changes

2024-12-16 13:06 UTC, blackplayerten commented on SunaTravel/FavoritePlaces/Views/FavoritePlaceCell.swift
> +    var place: Place
не прокидываем так модель
как минимум через getModel() -> Place
а еще лучше в протокол обернуть

2024-12-16 13:06 UTC, blackplayerten commented on SunaTravel/SearchTrip/Controllers/SearchPlaceViewController.swift
> +fileprivate struct UIConstants {
не оч нравится глобавильные константы
помещайте внутрь ко вьюхе

2024-12-16 13:06 UTC, blackplayerten commented on SunaTravel/SearchTrip/Controllers/SearchPlaceViewController.swift
> +class SearchPlacesViewController: UIViewController, UICollectionViewDelegate, UICollectionViewDataSource, UISearchBarDelegate {
отдельные делегаты

2024-12-16 13:06 UTC, blackplayerten commented on SunaTravel/SearchTrip/Controllers/SearchPlaceViewController.swift
> +    var viewModel = SearchPlacesViewModel()
протокол

2024-12-16 13:06 UTC, blackplayerten commented on SunaTravel/SearchTrip/Controllers/SearchPlaceViewController.swift
> +        collectionView.dataSource = self
в ините каждом проставлять

2024-12-16 13:06 UTC, blackplayerten commented on SunaTravel/SearchTrip/Controllers/SearchPlaceViewController.swift
> +        navigationItem.title = "Search"
не думали над локализацией?

2024-12-21 15:43 UTC, juliaplatova requested changes

2024-12-21 15:43 UTC, juliaplatova commented on SunaTravel/FavoritePlaces/Controllers/FavoritePlacesViewController.swift
> +        collectionView.register(FavoritePlaceCell.self, forCellWithReuseIdentifier: "FavoritePlaceCell")
есть возможность никогда не прописывать идентификатор, если вынести это в Extension

например:
```
collectionView.register(FavoritePlaceCell.self, forCellWithReuseIdentifier: FavoritePlaceCell.reuseID)
```

```
extension UICollectionViewCell {
    static var reuseID: String {
        return String(describing: self)
    }
}
```

2024-12-21 15:43 UTC, juliaplatova commented on SunaTravel/FavoritePlaces/Controllers/FavoritePlacesViewController.swift
> +        view.backgroundColor = .white
это тоже в UIConstants

2024-12-21 15:43 UTC, juliaplatova commented on SunaTravel/FavoritePlaces/Extensions/CollectionViewDelegate&DataSource.swift
> +        let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "FavoritePlaceCell", for: indexPath) as! FavoritePlaceCell
Force Unwrap (!) вообще никогда нельзя использовать, в случае регресса по кодовой базе, это краш в проде.

он есть, про него можно сказать на собеседовании, но даже если уверен, то не стоит
```
if let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "FavoritePlaceCell", for: indexPath) as? FavoritePlaceCell {
        let place = MockData.places[indexPath.item]
        cell.configure(with: place)
        return cell
} else {
        assertionFailure()
        return UICollectionViewCell()
}
```

2024-12-21 15:43 UTC, juliaplatova commented on SunaTravel/FavoritePlaces/Extensions/CollectionViewDelegate&DataSource.swift
> +        print("Selected Place: \(selectedPlace.title)")
// TODO : - или MARK: - в подобных местах надо добавить, чтобы после не забыть убрать

2024-12-21 15:43 UTC, juliaplatova commented on SunaTravel/FavoritePlaces/Extensions/CollectionViewDelegate&DataSource.swift
> +        let selectedPlace = MockData.places[indexPath.item]
в случае, если indexPath.item больше, чем количество мест в мокнутых данных (по ошибке в логике или из-за регресса), то это краш в проде, нужно доп. проверка

2024-12-21 15:43 UTC, juliaplatova commented on SunaTravel/FavoritePlaces/Models/Place.swift
> +struct Place {
из названия невидно, что это. модель данных, модель представления, вьюха
могу предложить название: PlaceModel (можно придумать нечто получше)

2024-12-21 15:43 UTC, juliaplatova commented on SunaTravel/FavoritePlaces/Views/FavoritePlaceCell.swift
> +protocol PlaceProvider {
варианта два:
1) по неймингу это либо IPlaceProvider или PlaceProviderProtocol
2) ExamplePlaceProvider надо переименовать в ExamplePlaceProviderImpl

потому что здесь уже не явно становится, где описание интерфейса, а где его реализация

2024-12-21 15:43 UTC, juliaplatova commented on SunaTravel/FavoritePlaces/Views/FavoritePlaceCell.swift
> +struct ExamplePlaceProvider: PlaceProvider {
провайдер в отдельный файл бы двинуть надо

Создать папку:
Providers
внутри неё
PlaceProvider
и туда все что нужно для его реализации

думаю, что провайдеров у вас будет много

2024-12-21 15:43 UTC, juliaplatova commented on SunaTravel/SearchTrip/Models/SearchPlaceViewModel.swift
> +            filteredPlaces = places.filter { place in
внутри класса/структуры place можно метод написать

2024-12-24 10:21 UTC, merged