Update README.md
iOS-vk-education/2024_1_SunaTeam pull request #21
Opened 2024-12-16 00:22 UTC by IvanTarasiuk

перенос из legacy-main

2024-12-16 13:11 UTC, blackplayerten requested changes

2024-12-16 13:11 UTC, blackplayerten commented on README.md
> +**Название проекта:** Трекер путешествий (рабочее название)
(рабочее название)  убрать

2024-12-16 13:11 UTC, blackplayerten commented on README.md
> +   - [**figma**](<https://www.figma.com/design/eKMyExcqCN6SA7bC7YzGfB/Suna-Travel-App?node-id=0-1&node-type=canvas&t=aSdNGv95nMuFL7Ly-0>)
это вынести до основного функционала

2024-12-16 13:11 UTC, blackplayerten commented on README.md
> +- **Frontend:** SwiftUI/UIKit
написать, что конкретно на суи, а что на ките сделано

2024-12-21 14:51 UTC, juliaplatova approved these changes
Хорошо, ветка переименована, все замечания поправлены

2024-12-21 14:51 UTC, merged