Задача №1: UI стартового экрана
iOS-vk-education/2024_1_SunaTeam pull request #3
Opened 2024-10-29 18:56 UTC by mylovelyserge

Добавил:
стартовый экран
экран авторизации
экран регистрации

2024-11-02 09:35 UTC, blackplayerten requested changes

2024-11-02 09:35 UTC, blackplayerten commented on .DS_Store
в gitignore

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam.xcodeproj/project.xcworkspace/xcuserdata/mylovelyserge.xcuserdatad/UserInterfaceState.xcuserstate
gitignore

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/Assets.xcassets/LaunchScreen.imageset/LaunchScreen.png
опционально: лучше в pdf загружать

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/Elements/ButtonsView.swift
> +    var height: CGFloat = 56
не пишем такие константы, всегда считаем их относительно высоты/ширины экрана

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/Elements/ButtonsView.swift
> +
наверное здесь вызов action() из поля структуры

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/Elements/ButtonsView.swift
> +                .padding(.top, paddingTop)
вынести в отдельное вью/функцию

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/Elements/ButtonsView.swift
лучше не Elements, а DesignSystem/Components
для цветов будет DesignSystem/Colors

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/Elements/ButtonsView.swift
> +    var action: () -> Void
в целом подумать, нужно ли такое количество полей
или они могут быть заданы по умолчанию исходя из цветов дс

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/Elements/ButtonsView.swift
> +                        .stroke(borderColor ?? Color.clear, lineWidth: borderColor != nil ? 1 : 0)
лучше Color.clear и константы у borderColor (1 или 0) вынести в отдельную приватную структуру defaultConfiguration, а не проставлять сразу в коде

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/AuthPage/AuthPageSystem.swift
пустые файлы пока удали

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/AuthPage/AuthPageView.swift
> +//  RegistrationPageView.swift
название файла не совпадает с именем структуры

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/AuthPage/AuthPageView.swift
> +            textColor: .white,
вынести по отдельным вью

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/AuthPage/AuthPageView.swift
> +                .font(/*@START_MENU_TOKEN@*/.title/*@END_MENU_TOKEN@*/)
что такое START_MENU_TOKEN?

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/AuthPage/AuthPageView.swift
> +                .fontWeight(.regular)
я думаю компонент ДС текст тоже должен быть создан
сделать для него несколько конфигураций: bold, regular
+ инит от текста добавьте
тогда текущие тексты будут подходить под эту конфигурацию и смотреться будет лучше

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/AuthPage/AuthPageView.swift
> +        .padding(.horizontal, 40)
40 кажется большой паддинг
может получится посчитать?

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/AuthPage/AuthPageView.swift
> +    var text: String
private 
или если будешь менять то скорее всего State

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/AuthPage/AuthPageView.swift
> +            .frame(width: 295, height: 58)
плохие константы
1. если константа > 30 стоит задуматься о ее вычислении
2. если отступы/размеры шрифтоы/чего угодно еще совпадают более 2 раз, то стоит вынести их в 
```
private structConstants { 
    static let padding: CGFloat = 20.0 
    static let paddingTop: CGFloat = 25.0 
    //... 
}
```

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/RegistrationPage/RegistrationPageSystem.swift
пока удалить

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/RegistrationPage/RegistrationPageView.swift
> +    var registerISDisabled: Bool {
registerIsDisabled
register -> signUp
непонятно к чему это относится? к кнопке? к самому "запросу" регистрации?
тогда стоит назвать signUpButtonIsDisabled
или еще лучше завести enum со стейтом signUpButton

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/RegistrationPage/RegistrationPageView.swift
> +struct RegistrationPageView: View {
SignUp

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/RegistrationPage/RegistrationPageView.swift
> +}
такой я уже видела в другом файле
если повторяется или конфигурация отличается минимально, то это один компонент из дс с 2 состояниями

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/RegistrationPage/RegistrationPageView.swift
> +}
поле ааода тоже компонент дс
секюрность можно добавить к этому компоненту как свойство

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/StartPage/Launch Screen.storyboard
пробел в названии убрать

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/StartPage/StartPageSystem.swift
> +    @ObservableState
enter

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/StartPage/StartPageSystem.swift
> +    struct State {
лучше перед подписать 
// MARK: - State
// MARK: - Actions

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/StartPage/StartPageSystem.swift
> +
не нужен отступ

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/StartPage/StartPageSystem.swift
> +        case registrationButtonTapped
разбить
```
enum Action {
    enum Button {
         authTapped
         signUpTapped
     }
}
```

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/StartPage/StartPageSystem.swift
> +                return .none
return не нужен

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/StartPage/StartPageSystem.swift
> +                return .none
return не нужен

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/StartPage/StartPageView.swift
> +    }
вынести

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/StartPage/StartPageView.swift
> +                    store.send(.authorizationButtonTapped)
кажется тут что-то вроде Action.Button.authTapped
не помню как точно пишется, но лучше указать, что эксшн напрямую из стора используется

2024-11-02 09:35 UTC, blackplayerten commented on SunaTeam/RegAndAuth/StartPage/StartPageView.swift
> +            .frame(width: 295.0, height: 36.0)
константы

2024-11-06 16:13 UTC, juliaplatova requested changes

2024-11-22 21:48 UTC, merged